name: build

on: 
  push:
    branches:
    - "*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Prepare
        run: |
          sudo apt update
          sudo apt install build-essential clang flex bison g++ gawk gcc-multilib g++-multilib \
            gettext git libncurses-dev libssl-dev python3-distutils rsync unzip zlib1g-dev \
            file wget
      - name: Build
        run: make
      - uses: actions/upload-artifact@v3
        with:
          name: firmware
          path: glbuilder/bin/*/target/*
      - uses: ncipollo/release-action@v1
        with:
          tag: 4.3.6
          artifacts: "glbuilder/bin/*/target/*.bin"
          allowUpdates: true
